name: Build and Upload

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build Linux and Windows binaries
        run: make all

      - name: Upload to Release
        uses: softprops/action-gh-release@master
        with:
          files: |
            build/*/Spinexr-Upscaler-*.zip
          name: Spinexr Upscaler ${{ env.BUILD_DATE }}
          tag_name: ${{ github.run_id }}
          body: |
            Hello World
