name: Build and Upload

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build Linux and Windows binaries
        run: make all

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v3
        with:
          name: Spinexr-Upscaler-linux
          path: build/Spinexr-Upscaler-linux.zip

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v3
        with:
          name: Spinexr-Upscaler-windows
          path: build/Spinexr-Upscaler-windows.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Linux artifact
        uses: actions/download-artifact@v3
        with:
          name: Spinexr-Upscaler-linux

      - name: Download Windows artifact
        uses: actions/download-artifact@v3
        with:
          name: Spinexr-Upscaler-windows

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            Spinexr-Upscaler-linux.zip
            Spinexr-Upscaler-windows.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
